[package]
name = "simpleserial-rs"
version = "0.1.0"
authors = ["Gijs Burghoorn <g.burghoorn@gmail.com>"]
edition = "2018"
build = "build.rs"

[dev-dependencies]
# cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
# cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"

[[example]]
name = "key-inverter"
